// =============================================================================
// Vivid-Lingua — Дэлгэрэнгүй асуултын сан (унших + сонсох)
// -----------------------------------------------------------------------------
// Үндсэн сангийн (id 1-52) дасгал бүрд 2-3 нарийвчилсан, бодит асуулт.
// Асуулт бүр сэжүүр (hint) ба зөв хариултын тайлбартай (explanation).
// Зөв хариултын байрлал санаатайгаар холилдсон тул "үргэлж Б" гэж таах боломжгүй.
// getReadingQuestions()/getListeningQuestions() эдгээрийг item-тэй нь нийлүүлдэг.
// =============================================================================

import type { QuizQuestion } from './library';

export const READING_QUESTIONS: Record<number, QuizQuestion[]> = {
  1: [
    { question: 'Анна хаана амьдардаг вэ?', choices: ['Улаанбаатарт', 'Берлинд', 'Мюнхенд'], correctIndex: 1,
      hint: '"Jetzt wohne ich in …" гэсэн өгүүлбэрийг ол.', explanation: '"Jetzt wohne ich in Berlin" — Анна Монголоос ирсэн ч одоо Берлинд амьдардаг.' },
    { question: 'Аннагийн хобби юу вэ?', choices: ['Ном унших', 'Зурах', 'Гүйх'], correctIndex: 0,
      hint: 'Сүүлчийн өгүүлбэр: "Mein Hobby ist …".', explanation: '"Mein Hobby ist Lesen" — Lesen нь "унших" гэсэн утгатай.' },
  ],
  2: [
    { question: 'Тэдний гэр бүл хэдэн хүнтэй вэ?', choices: ['Гурван', 'Таван', 'Дөрвөн'], correctIndex: 2,
      hint: '"Wir sind vier Personen" — vier гэдэг тоог сана.', explanation: '"Wir sind vier Personen: mein Vater, meine Mutter, mein Bruder und ich" — аав, ээж, дүү, би гэсэн 4 хүн.' },
    { question: 'Том хэн бэ, хэдэн настай вэ?', choices: ['Аав нь, 40 настай', 'Дүү нь, 10 настай', 'Нохой нь, 3 настай'], correctIndex: 1,
      hint: '"Mein Bruder heißt Tom …" өгүүлбэрийг хар.', explanation: '"Mein Bruder heißt Tom und ist zehn Jahre alt" — Том бол дүү нь, 10 настай. Нохойн нэр текстэд байхгүй.' },
  ],
  3: [
    { question: 'Тэр хэдэн цагт босдог вэ?', choices: ['7 цагт', '6 цагт', '8 цагт'], correctIndex: 0,
      hint: '"Ich stehe um sieben Uhr auf" — sieben = 7.', explanation: '"um sieben Uhr" гэдэг нь 7 цагт. 8 цагт ажилдаа явдаг гэдгийг бүү андуур.' },
    { question: 'Орой тэр юу хийдэг вэ?', choices: ['Кино театр явдаг', 'Найзуудтайгаа уулздаг', 'Хоол хийж, зурагт үздэг'], correctIndex: 2,
      hint: '"Am Abend …" гэж эхэлсэн өгүүлбэрийг ол.', explanation: '"Am Abend koche ich und sehe fern" — kochen (хоол хийх) + fernsehen (зурагт үзэх).' },
  ],
  4: [
    { question: 'Өгүүлэгч өөртөө юу захиалж байна вэ?', choices: ['Пицца', 'Шөл ба салат', 'Загас'], correctIndex: 1,
      hint: '"Ich bestelle …" гэсэн өгүүлбэрийг хар — найзных нь захиалгатай андуурч болохгүй.', explanation: '"Ich bestelle eine Suppe und einen Salat" — өгүүлэгч шөл, салат; пиццаг найз нь иддэг.' },
    { question: 'Тэд юу ууж байна вэ?', choices: ['Кофе ба цай', 'Дарс', 'Ус ба шүүс'], correctIndex: 2,
      hint: 'Сүүлчийн өгүүлбэр: "Wir trinken …".', explanation: '"Wir trinken Wasser und Saft" — Wasser (ус), Saft (шүүс).' },
  ],
  5: [
    { question: 'Тэр хэзээ супермаркет явдаг вэ?', choices: ['Бямба гарагт', 'Ням гарагт', 'Даваа гарагт'], correctIndex: 0,
      hint: '"Am Samstag …" — Samstag аль гараг вэ?', explanation: '"Am Samstag gehe ich in den Supermarkt" — Samstag нь Бямба гараг.' },
    { question: 'Текстээр аль нь зөв бэ?', choices: ['Тэр зөвхөн жимс авдаг', 'Алим маш шинэхэн байсан', 'Тэр картаар төлдөг'], correctIndex: 1,
      hint: '"Die Äpfel sind sehr frisch" өгүүлбэрийг сана.', explanation: 'Текстэд "Die Äpfel sind sehr frisch" гэсэн. Талх, сүү, өндөг ч авдаг тул зөвхөн жимс биш; төлбөрийн хэлбэр (карт) дурдаагүй, зөвхөн кассанд төлдөг гэсэн.' },
  ],
  6: [
    { question: 'Өнөөдөр цаг агаар ямар байна вэ?', choices: ['Бороотой, хүйтэн', 'Цастай', 'Нартай, дулаахан'], correctIndex: 2,
      hint: 'Эхний хоёр өгүүлбэрийг хар: "Die Sonne scheint …".', explanation: '"Die Sonne scheint und es ist warm" — нар гарч дулаахан байна. Бороо маргааш орно гэсэн.' },
    { question: 'Маргааш цаг агаар яах гэж байна вэ?', choices: ['Бороо орно', 'Нартай байна', 'Салхитай байна'], correctIndex: 0,
      hint: '"Morgen soll es … regnen" — regnen гэдэг үйл үгийг сана.', explanation: '"Morgen soll es aber regnen" — маргааш бороо орох төлөвтэй.' },
  ],
  7: [
    { question: 'Өгүүлэгч амралтын өдөр юу хийдэг вэ?', choices: ['Хөгжим тоглодог', 'Дугуй унадаг', 'Усанд сэлдэг'], correctIndex: 1,
      hint: '"Am Wochenende fahre ich Fahrrad" — Fahrrad гэж юу вэ?', explanation: '"Am Wochenende fahre ich Fahrrad" — Fahrrad fahren нь дугуй унах.' },
    { question: 'Эгч нь юу хийх дуртай вэ?', choices: ['Зурах', 'Хөлбөмбөг тоглох', 'Хөгжим сонсох'], correctIndex: 0,
      hint: 'Сүүлчийн өгүүлбэр: "Meine Schwester malt gern".', explanation: '"malt gern" — malen нь зурах. Хөлбөмбөг, хөгжим бол өгүүлэгчийн өөрийнх нь сонирхол.' },
  ],
  8: [
    { question: 'Хичээл хэдээс хэдэн цаг хүртэл үргэлжилдэг вэ?', choices: ['8-аас 1 цаг', '9-өөс 2 цаг', '10-аас 3 цаг'], correctIndex: 1,
      hint: '"von neun bis zwei Uhr" — neun ба zwei гэсэн тоонууд.', explanation: '"Unterricht von neun bis zwei Uhr" — 9-өөс 14 (2) цаг хүртэл.' },
    { question: 'Тэр завсарлагаанд юу иддэг вэ?', choices: ['Жижиг талх (Brötchen)', 'Шөл', 'Алим'], correctIndex: 0,
      hint: 'Сүүлчийн өгүүлбэр: "In der Pause esse ich …".', explanation: '"In der Pause esse ich ein Brötchen" — Brötchen бол жижиг талх.' },
  ],
  9: [
    { question: 'Орон сууц нь хэдэн өрөөтэй вэ?', choices: ['Гурван өрөө', 'Нэг өрөө', 'Хоёр өрөө'], correctIndex: 2,
      hint: '"Sie hat zwei Zimmer …" — zwei = ?', explanation: '"Sie hat zwei Zimmer, eine Küche und ein Bad" — хоёр өрөө, гал тогоо, угаалгын өрөө (гал тогоо, ванн нь өрөөний тоонд орохгүй).' },
    { question: 'Өгүүлэгчийн дуртай газар хаана вэ?', choices: ['Гал тогоо', 'Тагт (балкон)', 'Унтлагын өрөө'], correctIndex: 1,
      hint: '"Der Balkon ist mein Lieblingsplatz" — Lieblingsplatz гэдэг нь дуртай газар.', explanation: '"Der Balkon ist mein Lieblingsplatz" — тагт бол хамгийн дуртай газар нь.' },
  ],
  10: [
    { question: 'Мими хэдэн настай вэ?', choices: ['Гурван настай', 'Хоёр настай', 'Таван настай'], correctIndex: 0,
      hint: '"… und ist drei Jahre alt" — drei = ?', explanation: '"Sie heißt Mimi und ist drei Jahre alt" — 3 настай.' },
    { question: 'Мими хаана унтах дуртай вэ?', choices: ['Орон дээр', 'Цонхны тавцан дээр', 'Буйдан дээр'], correctIndex: 2,
      hint: '"Mimi schläft gern auf dem Sofa" — Sofa гэж юу вэ?', explanation: '"auf dem Sofa" — буйдан дээр унтах дуртай, өглөө бүр сүү уудаг.' },
  ],
  11: [
    { question: 'Сэрүүлэг хэдэн цагт дуугардаг вэ?', choices: ['7:15-д', '6:30-д', '7:30-д'], correctIndex: 1,
      hint: '"halb sieben" гэдэг нь германаар 6:30 гэсэн утгатай!', explanation: '"Mein Wecker klingelt um halb sieben" — halb sieben = долоо болоход хагас дутуу = 6:30. Энэ бол герман цагийн онцлог!' },
    { question: 'Автобус хэдэн цагт ирдэг вэ?', choices: ['7:15-д', '6:45-д', '7:45-д'], correctIndex: 0,
      hint: '"Viertel nach sieben" = 7 цагаас 15 минут өнгөрсөн.', explanation: '"Der Bus kommt um Viertel nach sieben" — Viertel nach = 15 минут өнгөрсөн, тиймээс 7:15.' },
  ],
  12: [
    { question: 'Өнөөдөр тэр юу өмссөн бэ?', choices: ['Цамц, шорт', 'Хүрэм, ороолт, бээлий', 'Зөвхөн малгай'], correctIndex: 1,
      hint: '"Ich trage …" гэсэн өгүүлбэрт гурван зүйл жагсаасан.', explanation: '"Ich trage eine Jacke, einen Schal und Handschuhe" — хүрэм (Jacke), ороолт (Schal), бээлий (Handschuhe). Өнөөдөр хүйтэн учраас.' },
    { question: 'Малгай нь ямар өнгөтэй вэ?', choices: ['Цэнхэр', 'Улаан', 'Хар'], correctIndex: 0,
      hint: '"Meine Mütze ist blau" — blau ямар өнгө вэ?', explanation: '"Meine Mütze ist blau" — blau нь цэнхэр.' },
  ],
  13: [
    { question: 'Бямба гарагт тэр юу хийдэг вэ?', choices: ['Ном уншдаг', 'Гэртээ үлддэг', 'Өвөө эмээ дээрээ очдог'], correctIndex: 2,
      hint: '"Am Samstag besuche ich …" — besuchen гэдэг нь зочлох.', explanation: '"Am Samstag besuche ich meine Großeltern" — Бямбад өвөө эмээ дээрээ очдог; ном уншиж гэртээ үлдэх нь Ням гарагийнх.' },
    { question: 'Ням гарагийн өдрөө тэр хэрхэн үнэлдэг вэ?', choices: ['Уйтгартай гэж боддог', 'Гоё гэж боддог', 'Ядаргаатай гэж боддог'], correctIndex: 1,
      hint: 'Сүүлчийн өгүүлбэр: "Das finde ich schön".', explanation: '"Das finde ich schön" — finden + schön нь "гоё гэж үзэх/бодох" гэсэн хэллэг.' },
  ],
  14: [
    { question: 'Ээж нь хэдэн нас хүрэх гэж байна вэ?', choices: ['50', '40', '60'], correctIndex: 0,
      hint: '"Sie wird fünfzig Jahre alt" — fünfzig = ?', explanation: '"Sie wird fünfzig Jahre alt" — fünfzig нь 50. (vierzig=40, sechzig=60-тай бүү андуур!)' },
    { question: 'Өгүүлэгч төрсөн өдөрт юу бэлдэж байна вэ?', choices: ['Бэлэг худалдаж авна', 'Ресторан захиална', 'Цэцэг авч, бялуу хийнэ'], correctIndex: 2,
      hint: '"Ich kaufe Blumen und backe einen Kuchen" — backen гэдэг нь жигнэх.', explanation: '"Ich kaufe Blumen und backe einen Kuchen" — цэцэг авч, бялуу барьж өгнө. Бүх гэр бүл цуглана.' },
  ],
  15: [
    { question: 'Түүний хотод юу юу байдаг вэ?', choices: ['Олон дэлгүүр, кафе, цэцэрлэгт хүрээлэн', 'Зөвхөн үйлдвэрүүд', 'Далайн эрэг'], correctIndex: 0,
      hint: '"Hier gibt es …" гэсэн өгүүлбэрт жагсаасан.', explanation: '"viele Geschäfte, Cafés und einen schönen Park" — дэлгүүр, кафе, сайхан цэцэрлэгт хүрээлэн.' },
    { question: 'Тэр юугаар зорчдог вэ?', choices: ['Автобусаар', 'Машинаар', 'Метрогоор'], correctIndex: 2,
      hint: '"Ich fahre mit der U-Bahn" — U-Bahn гэж юу вэ?', explanation: '"mit der U-Bahn" — U-Bahn (Untergrundbahn) нь метро.' },
  ],
  16: [
    { question: 'Өглөөний цайнд тэр юу идэх дуртай вэ?', choices: ['Зөвхөн жимс', 'Бяслагтай талх', 'Будаа'], correctIndex: 1,
      hint: '"Brot mit Käse" — Käse гэдэг нь бяслаг.', explanation: '"esse ich gern Brot mit Käse" — бяслагтай талх идэх дуртай, заримдаа өндөг ч иддэг.' },
    { question: 'Амралтын өдөр өглөөний цай нь юугаараа онцлог вэ?', choices: ['Идэхгүй алгасдаг', 'Кафед иддэг', 'Удаан өглөөлдөг'], correctIndex: 2,
      hint: 'Сүүлчийн өгүүлбэр: "frühstücke ich lange".', explanation: '"Am Wochenende frühstücke ich lange" — амралтын өдөр яаралгүй, удаан өглөөний цай уудаг.' },
  ],
  17: [
    { question: 'Тэд хаанаас танил вэ?', choices: ['Сургуулиас', 'Ажлаас', 'Спорт клубээс'], correctIndex: 0,
      hint: '"Wir kennen uns seit der Schule" — seit гэдэг нь "-аас хойш".', explanation: '"seit der Schule" — сургуулийн үеэс хойш танилууд.' },
    { question: 'Паул ямар хүн бэ?', choices: ['Нухацтай, чимээгүй', 'Хөгжилтэй, тусархуу', 'Залхуу'], correctIndex: 1,
      hint: '"Er ist lustig und hilft mir immer" — lustig + helfen.', explanation: '"lustig" нь хөгжилтэй, "hilft mir immer" нь үргэлж тусалдаг — тусархуу.' },
  ],
  18: [
    { question: 'Мариа Лизаг хаашаа урьж байна вэ?', choices: ['Ресторанд', 'Театрт', 'Кино театрт'], correctIndex: 2,
      hint: '"Wir können ins Kino gehen" — Kino гэж юу вэ?', explanation: '"Wir können ins Kino gehen" — кино театр руу явахыг санал болгож байна.' },
    { question: 'Мариа Лизагаас юу хүсэж байна вэ?', choices: ['Буцааж залгахыг', 'Тийз авахыг', 'Эрт ирэхийг'], correctIndex: 0,
      hint: 'Сүүлчийн өгүүлбэр: "Ruf mich bitte zurück!"', explanation: '"Ruf mich bitte zurück" — zurückrufen нь буцааж залгах. Кино 8 цагт эхэлнэ.' },
  ],
  19: [
    { question: 'Түүний мэргэжил юу вэ?', choices: ['Эмч', 'Багш', 'Сувилагч'], correctIndex: 2,
      hint: '"Ich bin Krankenschwester" — Kranken + Schwester.', explanation: '"Krankenschwester" нь сувилагч (эмэгтэй). Эмнэлэгт ажилладаг ч эмч биш.' },
    { question: 'Тэр ажлаа хэрхэн үнэлдэг вэ?', choices: ['Хүнд боловч дуртай', 'Амархан бөгөөд уйтгартай', 'Цалин сайтай'], correctIndex: 0,
      hint: '"Die Arbeit ist schwer, aber …" — aber-ийн ард гол санаа.', explanation: '"Die Arbeit ist schwer, aber ich mag sie" — ажил хүнд ч би дуртай.' },
  ],
  20: [
    { question: 'Зах дээрээс тэр юу авдаг вэ?', choices: ['Талх, сүү, өндөг', 'Улаан лооль, өргөст хэмх, гадил', 'Мах, загас'], correctIndex: 1,
      hint: '"Ich kaufe Tomaten, Gurken und Bananen".', explanation: 'Tomaten (улаан лооль), Gurken (өргөст хэмх), Bananen (гадил) — гурвууланг нь зах дээрээс авдаг.' },
    { question: 'Худалдагч ямар хүн бэ?', choices: ['Найрсаг', 'Яаруу', 'Дуугүй'], correctIndex: 0,
      hint: '"Der Verkäufer ist sehr freundlich" — freundlich.', explanation: '"sehr freundlich" — маш найрсаг. Бараа нь хямд бөгөөд сайн гэж нэмж хэлсэн.' },
  ],
  21: [
    { question: 'Тэр Хамбург руу юугаар явах вэ?', choices: ['Онгоцоор', 'Автобусаар', 'Галт тэргээр'], correctIndex: 2,
      hint: '"Ich nehme den Zug um neun Uhr" — Zug гэж юу вэ?', explanation: '"Ich nehme den Zug" — Zug нь галт тэрэг; 9 цагийн галт тэргэнд сууна.' },
    { question: 'Хамбургт тэр юу үзэх вэ, хэр удаан байх вэ?', choices: ['Музей, хоёр хоног', 'Театр, гурван хоног', 'Зах, нэг хоног'], correctIndex: 0,
      hint: '"besuche ich ein Museum" + "nur zwei Tage".', explanation: '"In Hamburg besuche ich ein Museum. Ich bleibe nur zwei Tage" — музей үзээд хоёрхон хоног байна.' },
  ],
  22: [
    { question: 'Өвчтөнд ямар шинж тэмдэг байна вэ?', choices: ['Ханиад, хамар битүүрэх', 'Толгой өвдөж, халуурах', 'Гэдэс өвдөх'], correctIndex: 1,
      hint: '"Mein Kopf tut weh und ich habe Fieber" — Kopf + Fieber.', explanation: '"Mein Kopf tut weh" (толгой өвдөж) + "ich habe Fieber" (халуурч байна).' },
    { question: 'Эмч юу зөвлөсөн бэ?', choices: ['Эм уух', 'Гүйлт хийх', 'Их ус ууж, унтах'], correctIndex: 2,
      hint: '"viel Wasser trinken und schlafen".', explanation: '"ich soll viel Wasser trinken und schlafen" — их ус ууж, унтаж амрахыг зөвлөсөн. Эмийн тухай дурдаагүй.' },
  ],
  23: [
    { question: 'Аялал хэр удаан үргэлжилдэг вэ?', choices: ['20 минут', '12 минут', '30 минут'], correctIndex: 0,
      hint: '"Die Fahrt dauert zwanzig Minuten" — zwanzig = ?', explanation: '"zwanzig Minuten" — 20 минут.' },
    { question: 'Автобус дүүрэн байвал тэр яадаг вэ?', choices: ['Дараагийн автобусыг хүлээдэг', 'Зогсох хэрэгтэй болдог', 'Таксигаар явдаг'], correctIndex: 1,
      hint: '"Dann muss ich stehen" — stehen гэдэг нь зогсох.', explanation: '"Manchmal ist der Bus voll. Dann muss ich stehen" — суудалгүй тул зогсоод явдаг.' },
  ],
  24: [
    { question: 'Кафед тэр юу ууж, юу иддэг вэ?', choices: ['Цай ба жигнэмэг', 'Шүүс ба пицца', 'Каппучино ба бялуу'], correctIndex: 2,
      hint: '"Cappuccino" ба "ein Stück Kuchen".', explanation: '"Ich trinke einen Cappuccino und esse ein Stück Kuchen" — каппучино + нэг зүсэм бялуу.' },
    { question: 'Кафед түүнд юу таалагддаг вэ?', choices: ['Уншиж, хүмүүсийг ажиглаж болдог', 'Хөгжим чанга байдаг', 'Wifi хурдтай'], correctIndex: 0,
      hint: '"Hier kann ich lesen und Leute beobachten".', explanation: '"lesen und Leute beobachten" — ном уншиж, хүмүүсийг ажиглах; маш нам гүм (ruhig) газар.' },
  ],
  25: [
    { question: 'Долоо хоногт хэдэн удаа фитнес явдаг вэ?', choices: ['Гурван удаа', 'Хоёр удаа', 'Өдөр бүр'], correctIndex: 1,
      hint: '"Zweimal pro Woche" — zweimal = хоёр удаа.', explanation: '"Zweimal pro Woche gehe ich ins Fitnessstudio" — долоо хоногт хоёр удаа.' },
    { question: 'Ням гарагт тэр юу хийдэг вэ?', choices: ['Цэцэрлэгт гүйдэг', 'Усанд сэлдэг', 'Амардаг'], correctIndex: 0,
      hint: '"Am Sonntag jogge ich im Park" — joggen.', explanation: '"jogge ich im Park" — цэцэрлэгт хүрээлэнд гүйдэг. Спорт түүнийг эрүүл, аз жаргалтай болгодог.' },
  ],
  26: [
    { question: 'Зуны улирал ямар вэ?', choices: ['Хүйтэн, богино өдөртэй', 'Бороотой', 'Дулаахан, урт өдөртэй'], correctIndex: 2,
      hint: '"Im Sommer ist es warm und die Tage sind lang".', explanation: '"warm" (дулаахан) + "die Tage sind lang" (өдрүүд урт).' },
    { question: 'Түүний дуртай улирал юу вэ?', choices: ['Хавар', 'Зун', 'Өвөл'], correctIndex: 0,
      hint: 'Сүүлчийн өгүүлбэр: "Mein Lieblingsjahreszeit ist der Frühling".', explanation: '"der Frühling" — хавар. Зун, өвлийн тухай зөвхөн тайлбарласан, дуртай нь хавар.' },
  ],
  27: [
    { question: 'Ангид хэдэн оюутан байдаг вэ?', choices: ['15', '5', '50'], correctIndex: 0,
      hint: '"fünfzehn Studenten" — fünfzehn = 15 (fünfzig = 50-тай андуурахгүй!).', explanation: '"In meiner Klasse sind fünfzehn Studenten" — fünfzehn нь 15.' },
    { question: 'Багш ямар хүн бэ?', choices: ['Хатуу, шаардлагатай', 'Эелдэг, тэвчээртэй', 'Залуу, хөгжилтэй'], correctIndex: 1,
      hint: '"Sie ist nett und geduldig" — geduldig гэдэг нь тэвчээртэй.', explanation: '"nett und geduldig" — эелдэг (nett), тэвчээртэй (geduldig). Нэр нь хатагтай Шмидт.' },
  ],
  28: [
    { question: 'Өгүүлэгч өөрөө юу хийдэг вэ?', choices: ['Хоол хийдэг', 'Цонх угаадаг', 'Өрөөгөө цэгцэлж, хувцас угаадаг'], correctIndex: 2,
      hint: '"Ich räume mein Zimmer auf und wasche die Wäsche".', explanation: '"aufräumen" (цэгцлэх) + "Wäsche waschen" (хувцас угаах) — өгүүлэгчийн ажил; хоолыг дүү нь хийдэг.' },
    { question: 'Хамтдаа ажиллахад юу болдог вэ?', choices: ['Хурдан болдог', 'Удаан болдог', 'Маргаан гардаг'], correctIndex: 0,
      hint: 'Сүүлчийн өгүүлбэр: "Zusammen geht es schnell".', explanation: '"Zusammen geht es schnell" — хамтдаа бол ажил хурдан бүтдэг.' },
  ],
  29: [
    { question: 'Тэд хаана, хэнтэй амарсан бэ?', choices: ['Ууланд найзуудтайгаа', 'Далайд гэр бүлээрээ', 'Хотод ганцаараа'], correctIndex: 1,
      hint: '"mit meiner Familie am Meer" — Meer гэдэг нь далай.', explanation: '"Letzten Sommer war ich mit meiner Familie am Meer" — өнгөрсөн зун гэр бүлээрээ далайд.' },
    { question: 'Тэд өдөр бүр юу хийдэг байсан бэ?', choices: ['Усанд сэлж, элсэн цайз барьдаг', 'Зах зээл үздэг', 'Музей үздэг'], correctIndex: 0,
      hint: '"sind wir geschwommen und haben Sandburgen gebaut".', explanation: 'schwimmen (усанд сэлэх) + Sandburgen bauen (элсэн цайз барих) — Perfekt хэлбэрээр.' },
    { question: 'Орой тэд юу иддэг байсан бэ?', choices: ['Пицца', 'Шарсан мах', 'Загас'], correctIndex: 2,
      hint: '"Abends haben wir Fisch gegessen" — Fisch.', explanation: '"Fisch gegessen" — далайн эрэгт орой бүр загас иддэг байжээ.' },
  ],
  30: [
    { question: 'Буудал руу яаж очих вэ?', choices: ['Чигээрээ яваад зүүн тийш эргэх', 'Чигээрээ яваад баруун тийш эргэх', 'Автобусанд суух'], correctIndex: 0,
      hint: '"geradeaus bis zur Ampel. Dann biegen Sie links ab" — links нь зүүн.', explanation: 'Гэрлэн дохио хүртэл чигээрээ (geradeaus), дараа нь зүүн (links) эргэнэ.' },
    { question: 'Буудал хаана байрладаг вэ, явганаар хэр хол вэ?', choices: ['Банкны хажууд, 10 минут', 'Шуудангийн хажууд, 5 минут', 'Сургуулийн ард, 15 минут'], correctIndex: 1,
      hint: '"neben der Post" + "fünf Minuten zu Fuß".', explanation: '"Der Bahnhof ist neben der Post. Es sind nur fünf Minuten zu Fuß" — шуудангийн хажууд, явганаар 5 минут.' },
  ],
  31: [
    { question: 'Сарагийн сайхан мэдээ юу вэ?', choices: ['Хурим хийнэ', 'Шинэ машинтай болсон', 'Мюнхенд шинэ ажил олсон'], correctIndex: 2,
      hint: '"Ich habe einen neuen Job in München gefunden".', explanation: '"einen neuen Job in München gefunden" — Мюнхен хотод шинэ ажил олсон нь мэдээ.' },
    { question: 'Сара дараа сард юу хийх вэ?', choices: ['Нүүнэ', 'Амарна', 'Шалгалт өгнө'], correctIndex: 0,
      hint: '"Nächsten Monat ziehe ich um" — umziehen гэдэг нь нүүх.', explanation: '"ziehe ich um" — umziehen (салдаг угтвартай үйл үг) нь нүүх; Максыг зочлохыг урьсан.' },
  ],
  32: [
    { question: 'Гоймонг хэдэн минут чанах вэ?', choices: ['5 минут', '10 минут', '20 минут'], correctIndex: 1,
      hint: '"koche ich die Nudeln zehn Minuten" — zehn = ?', explanation: '"zehn Minuten" — 10 минут чанана.' },
    { question: 'Соусыг юу юугаар хийдэг вэ?', choices: ['Улаан лооль, сонгино, сармис', 'Цөцгий, мөөг', 'Бяслаг, гахайн мах'], correctIndex: 0,
      hint: '"aus Tomaten, Zwiebeln und Knoblauch".', explanation: 'Tomaten (улаан лооль), Zwiebeln (сонгино), Knoblauch (сармис) — бяслагийг зөвхөн эцэст нь дээрээс нь нэмдэг.' },
  ],
  33: [
    { question: 'Өглөө тэр юу хийдэг вэ?', choices: ['Хурал хийдэг', 'Тайлан бичдэг', 'Имэйл уншиж, үйлчлүүлэгчидтэй ярьдаг'], correctIndex: 2,
      hint: '"lese ich meine E-Mails und telefoniere mit Kunden".', explanation: '"Am Morgen lese ich meine E-Mails und telefoniere mit Kunden" — имэйл + утасны яриа.' },
    { question: 'Ажлын дараа тэр ихэвчлэн юу хийдэг вэ?', choices: ['Шууд гэртээ харьдаг', 'Хамт олонтойгоо кофе уудаг', 'Фитнес явдаг'], correctIndex: 1,
      hint: '"Nach der Arbeit treffe ich oft Kollegen zum Kaffee".', explanation: '"treffe ich oft Kollegen zum Kaffee" — хамт олонтойгоо кофе уухаар уулздаг.' },
  ],
  34: [
    { question: 'Тэд ямар орон сууц хайж байна вэ?', choices: ['Гурван өрөөтэй, хэт үнэтэй биш', 'Хоёр өрөөтэй, төвд', 'Том байшин, цэцэрлэгтэй'], correctIndex: 0,
      hint: '"Sie soll drei Zimmer haben und nicht zu teuer sein".', explanation: 'Гурван өрөөтэй (drei Zimmer), хэт үнэтэй биш (nicht zu teuer) байх ёстой.' },
    { question: 'Тэдэнд юу чухал вэ?', choices: ['Лифт ба зоорь', 'Тагт ба машины зогсоол', 'Шинэ гал тогоо'], correctIndex: 1,
      hint: '"Wichtig ist ein Balkon und ein Platz für das Auto".', explanation: 'Balkon (тагт) + Platz für das Auto (машины зогсоол) — хамгийн дуртай нь төвд амьдрах.' },
  ],
  35: [
    { question: 'Галт тэрэг хэдэн цагт, хэддүгээр замаас хөдөлдөг вэ?', choices: ['11:30-д, 2-р замаас', '10:00-д, 6-р замаас', '10:30-д, 4-р замаас'], correctIndex: 2,
      hint: '"halb elf" = 10:30 (арван нэг болоход хагас дутуу)!', explanation: '"um halb elf von Gleis vier" — halb elf нь 10:30, Gleis vier нь 4-р зам.' },
    { question: 'Галт тэргэнд тэр юу хийдэг вэ?', choices: ['Цонхны суудалд ном уншдаг', 'Унтдаг', 'Хөгжим сонсдог'], correctIndex: 0,
      hint: '"Ich finde einen Fensterplatz und lese ein Buch".', explanation: 'Fensterplatz (цонхны суудал) олж ном уншдаг; хоёр цагийн дараа Кёльнд очно.' },
  ],
  36: [
    { question: 'Гэр бүлүүд хэзээ цуглардаг вэ?', choices: ['12-р сарын 31-нд', '12-р сарын 24-нд', '1-р сарын 1-нд'], correctIndex: 1,
      hint: '"Die Familien treffen sich am 24. Dezember".', explanation: 'Германд Зул сарын гол баяр 12-р сарын 24-ний орой (Heiligabend) болдог.' },
    { question: 'Хүүхдүүд юу авдаг вэ?', choices: ['Мөнгө', 'Чихэр', 'Бэлэг'], correctIndex: 2,
      hint: '"Die Kinder bekommen Geschenke" — Geschenke.', explanation: '"bekommen Geschenke" — бэлэг авдаг; гэр бүлүүд гацуур чимэглэж, хамт хооллодог.' },
  ],
  37: [
    { question: 'Цэнхэр пальто яагаад аваагүй вэ?', choices: ['Хэт үнэтэй байсан', 'Таараагүй', 'Өнгө нь таалагдаагүй'], correctIndex: 0,
      hint: '"passt gut, aber er ist zu teuer" — aber-ийн ард шалтгаан.', explanation: '"Der blaue Mantel passt gut, aber er ist zu teuer" — сайхан таарсан ч хэт үнэтэй.' },
    { question: 'Эцэст нь тэр ямар пальто авсан бэ?', choices: ['Цэнхэрийг бүтэн үнээр', 'Саарлыг хямдралтай үнээр', 'Юу ч аваагүй'], correctIndex: 1,
      hint: '"kaufe ich den grauen im Angebot" — im Angebot нь хямдралтай.', explanation: '"den grauen im Angebot" — хямдралд байсан саарал пальтог авсан.' },
  ],
  38: [
    { question: 'Бямба гарагт цаг агаар ямар байх вэ?', choices: ['Өдөржин бороотой', 'Нартай, үдээс хойш үүлшинэ', 'Цастай'], correctIndex: 1,
      hint: '"Am Samstag scheint die Sonne, aber am Nachmittag kommen Wolken".', explanation: 'Эхлээд нартай, гэхдээ үдээс хойш үүл гарч ирнэ — өөрчлөгдөнө гэдгийг "wechselhaft" гэсэн.' },
    { question: 'Температур хэдэн хэм орчим байх вэ?', choices: ['5 хэм', '25 хэм', '15 хэм'], correctIndex: 2,
      hint: '"bei fünfzehn Grad" — fünfzehn = ?', explanation: '"Die Temperaturen liegen bei fünfzehn Grad" — 15 хэм орчим.' },
  ],
  39: [
    { question: 'Театрын тийзний талаар юу мэдэгдэж байна вэ?', choices: ['Хоёр тийз аль хэдийн авсан', 'Тийз дууссан', 'Үүдэнд авна'], correctIndex: 0,
      hint: '"Ich habe schon zwei Karten gekauft" — schon нь "аль хэдийн".', explanation: '"schon zwei Karten gekauft" — хоёр тийзийг урьдчилж авчихсан.' },
    { question: 'Театрын өмнө тэд хаана хооллох вэ?', choices: ['Гэртээ', 'Театрын кафед', 'Итали ресторанд'], correctIndex: 2,
      hint: '"Vorher essen wir in einem italienischen Restaurant".', explanation: '"Vorher" (өмнө нь) итали ресторанд хооллоно; найз бүсгүй нь хамт явна.' },
  ],
  40: [
    { question: 'Хүүхэд байхдаа тэр хаана амьдардаг байсан бэ?', choices: ['Том хотод', 'Тосгонд', 'Далайн эрэгт'], correctIndex: 1,
      hint: '"wohnte ich in einem Dorf" — Dorf гэдэг нь тосгон.', explanation: '"Als ich ein Kind war, wohnte ich in einem Dorf" — Präteritum хэлбэрээр өнгөрснийг өгүүлж байна.' },
    { question: 'Зун тэр юу хийдэг байсан бэ?', choices: ['Өдөржин гадаа тоглодог байсан', 'Ном уншдаг байсан', 'Ажилладаг байсан'], correctIndex: 0,
      hint: '"spielte ich den ganzen Tag draußen" — draußen нь гадаа.', explanation: '"Im Sommer spielte ich den ganzen Tag draußen" — олон модтой том цэцэрлэгтэй байсан тул өдөржин гадаа тоглодог байжээ. Энэ үеийг их санадаг.' },
  ],
  41: [
    { question: 'Тэр яагаад герман хэл сурдаг вэ?', choices: ['Ажилд орохын тулд', 'Аялахын тулд', 'Германд суралцахын тулд'], correctIndex: 2,
      hint: '"weil ich in Deutschland studieren möchte" — weil нь шалтгаан заана.', explanation: '"weil ich in Deutschland studieren möchte" — Германд их сургуульд суралцах хүсэлтэй учраас.' },
    { question: 'Эхэндээ түүнд юу хэцүү байсан бэ?', choices: ['Дүрэм, ялангуяа артикль', 'Дуудлага', 'Сонсох'], correctIndex: 0,
      hint: '"war die Grammatik schwer, besonders die Artikel".', explanation: '"die Grammatik …, besonders die Artikel" — дүрэм, тэр дундаа der/die/das артикль хэцүү байжээ.' },
    { question: 'Одоо тэр юу чаддаг болсон бэ?', choices: ['Роман уншдаг', 'Энгийн яриа хийж, радио ойлгодог', 'Алдаагүй бичдэг'], correctIndex: 1,
      hint: '"Inzwischen kann ich schon …" өгүүлбэрийг хар.', explanation: '"einfache Gespräche führen und verstehe vieles im Radio" — өдөр бүр дасгал хийсний үр дүн.' },
  ],
  42: [
    { question: 'Машины оронд юу хэрэглэхийг санал болгож байна вэ?', choices: ['Мотоцикл', 'Дугуй', 'Автобус'], correctIndex: 1,
      hint: '"mit dem Fahrrad fahren statt mit dem Auto" — statt нь "оронд нь".', explanation: '"mit dem Fahrrad fahren statt mit dem Auto" — машины оронд дугуй унах.' },
    { question: 'Текстийн гол санаа юу вэ?', choices: ['Байгаль хамгаалал маш хэцүү', 'Зөвхөн засгийн газар хариуцлагатай', 'Жижиг алхамууд том өөрчлөлт авчирдаг'], correctIndex: 2,
      hint: 'Сүүлчийн өгүүлбэр: "Kleine Schritte machen einen großen Unterschied".', explanation: 'Өдөр тутмын жижиг үйлдлүүд (хог ялгах, дугуй унах, хуванцар багасгах) нийлээд том нөлөөтэй гэсэн санаа.' },
  ],
  43: [
    { question: 'Интернэтийн ачаар бид юу хийж чаддаг болсон бэ?', choices: ['Гэрээс ажиллаж, худалдан авч, гадаад найзуудтай ярих', 'Зөвхөн кино үзэх', 'Зөвхөн тоглоом тоглох'], correctIndex: 0,
      hint: '"von zu Hause arbeiten, einkaufen und … sprechen".', explanation: 'Гурван боломжийг жагсаасан: гэрээс ажиллах, худалдан авалт, өөр орны найзуудтай ярих.' },
    { question: 'Зохиогчийн анхааруулга юу вэ?', choices: ['Интернэт хэт үнэтэй', 'Өдөржин дэлгэцийн өмнө суух нь эрүүл бус', 'Онлайн худалдаа аюултай'], correctIndex: 1,
      hint: '"Trotzdem sollte man nicht …" — trotzdem нь "гэсэн ч".', explanation: '"nicht den ganzen Tag am Bildschirm sitzen, denn das ist ungesund" — дэлгэцийн цагийг хязгаарлахыг сануулсан.' },
  ],
  44: [
    { question: 'Таван жилийн дараа тэр юу хиймээр байна вэ?', choices: ['Сургуулиа төгсөж, инженерээр ажиллах', 'Эмч болох', 'Ресторан нээх'], correctIndex: 0,
      hint: '"möchte ich mein Studium beenden und als Ingenieurin arbeiten".', explanation: '"Studium beenden" (сургууль төгсөх) + "als Ingenieurin arbeiten" (инженерээр ажиллах).' },
    { question: 'Түүнд хамгийн чухал нь юу вэ?', choices: ['Алдартай болох', 'Их мөнгө олох', 'Таалагдах ажил олох'], correctIndex: 2,
      hint: '"Wichtig ist mir, dass …" өгүүлбэрийг хар.', explanation: '"eine Arbeit finde, die mir Spaß macht" — таашаал өгөх ажил олох нь хамгийн чухал.' },
  ],
  45: [
    { question: 'Эрүүл амьдрал ямар гурван зүйлээс бүрддэг вэ?', choices: ['Хоол, хөдөлгөөн, нойр', 'Спорт, ажил, амралт', 'Эм, витамин, ус'], correctIndex: 0,
      hint: '"aus drei Dingen: gutem Essen, Bewegung und genug Schlaf".', explanation: 'Сайн хоол (Essen), хөдөлгөөн (Bewegung), хангалттай нойр (Schlaf) — энэ гурав.' },
    { question: 'Текстээр юу "аль хэдийн хангалттай" вэ?', choices: ['Фитнесийн гишүүнчлэл', 'Өдөр бүр алхах', 'Марафон гүйх'], correctIndex: 1,
      hint: '"Dabei reicht schon ein täglicher Spaziergang" — reichen нь хүрэлцэх.', explanation: '"reicht schon ein täglicher Spaziergang" — өдөр бүрийн зугаалга л хангалттай; эрүүл амьдардаг хүн ховор өвддөг.' },
  ],
  46: [
    { question: 'Хотын давуу талд юу ордог вэ?', choices: ['Нам гүм, цэвэр агаар', 'Хямд үнэ', 'Дэлгүүр, ажил, соёл их'], correctIndex: 2,
      hint: '"In der Stadt gibt es viele Geschäfte, Jobs und Kultur".', explanation: 'Хотод дэлгүүр, ажлын байр, соёл их; гэхдээ чимээ шуугиантай, үнэтэй.' },
    { question: 'Зохиогч өөрөө аль амьдралыг илүүд үздэг вэ?', choices: ['Хөдөөгийнхийг — илүү тайван гэж үздэг', 'Хотынхыг — илүү сонирхолтой гэж үздэг', 'Аль алиныг адилхан гэж үздэг'], correctIndex: 0,
      hint: '"Ich persönlich finde das Landleben entspannter".', explanation: '"das Landleben entspannter" — хөдөөгийн амьдралыг илүү тайван (entspannt) гэж хувьдаа үздэг.' },
  ],
  47: [
    { question: 'Ажлын анкетад юу юу багтдаг вэ?', choices: ['Зураг ба диплом', 'Намтар ба өргөдөл', 'Гэрчилгээ ба паспорт'], correctIndex: 1,
      hint: '"Dazu gehören ein Lebenslauf und ein Anschreiben".', explanation: 'Lebenslauf (намтар) + Anschreiben (өргөдөл/мотивацийн захидал) — энэ хоёр заавал байна.' },
    { question: 'Өргөдөлд (Anschreiben) юу тайлбарладаг вэ?', choices: ['Цалингийн хүлээлтээ', 'Яагаад тухайн ажлыг хүсэж байгаагаа', 'Гэр бүлийн байдлаа'], correctIndex: 1,
      hint: '"Im Anschreiben erklärt man, warum …".', explanation: '"warum man die Stelle möchte" — яагаад энэ ажлын байрыг хүсэж буйгаа тайлбарладаг; алдаагүй, найрсаг бичих нь чухал.' },
  ],
  48: [
    { question: 'Музейд түүнд юу онцгой таалагдсан бэ?', choices: ['Шинэ үеийн баримал', 'Музейн барилга', 'Голын эрэг дэх хотын эртний зураг'], correctIndex: 2,
      hint: '"Besonders gut gefiel mir ein altes Gemälde …".', explanation: '"ein altes Gemälde von einer Stadt am Fluss" — голын эрэг дэх хотыг дүрсэлсэн эртний зураг.' },
    { question: 'Хөтөч юу хийсэн бэ?', choices: ['Зургуудын түүхийг тайлбарласан', 'Тийз шалгасан', 'Зураг зурж үзүүлсэн'], correctIndex: 0,
      hint: '"Ein Führer erklärte die Geschichte der Bilder".', explanation: '"erklärte die Geschichte der Bilder" — зургуудын түүхийг тайлбарласан; үзвэр үнэ цэнэтэй байжээ ("hat sich gelohnt").' },
  ],
  49: [
    { question: 'Сайн дурын ажилтнууд хэнтэй ажилладаг жишээ дурдсан бэ?', choices: ['Малчидтай', 'Өндөр настан, хүүхдүүдтэй', 'Оюутнуудтай'], correctIndex: 1,
      hint: '"zum Beispiel mit alten Leuten oder mit Kindern".', explanation: '"mit alten Leuten oder mit Kindern" — өндөр настан эсвэл хүүхдүүдтэй ажилладаг жишээ.' },
    { question: 'Тэд мөнгө авдаггүй ч юу авдаг вэ?', choices: ['Бэлэг', 'Үнэмлэх', 'Хэрэгтэй хүн гэдгээ мэдрэх мэдрэмж'], correctIndex: 2,
      hint: '"aber sie fühlen sich nützlich" — nützlich нь хэрэгтэй.', explanation: '"sie fühlen sich nützlich" — нийгэмд хэрэгтэй гэдгээ мэдэрдэг; ийм ажил нийгэмд чухал.' },
  ],
  50: [
    { question: 'Анх Германд ирэхэд түүнд ямар санагдсан бэ?', choices: ['Төөрсөн мэт, бүх юм шинэ', 'Гэртээ байгаа мэт', 'Уйтгартай'], correctIndex: 0,
      hint: '"war alles neu … fühlte mich verloren" — verloren нь төөрсөн.', explanation: '"alles neu für mich … fühlte mich verloren" — хүмүүсийг бараг ойлгохгүй, төөрсөн мэт байжээ.' },
    { question: 'Найрсаг эмэгтэй юунд тусалсан бэ?', choices: ['Байр олоход', 'Зөв автобус олоход', 'Бичиг баримт бөглөхөд'], correctIndex: 1,
      hint: '"half mir, den richtigen Bus zu finden".', explanation: '"den richtigen Bus zu finden" — зөв автобусыг олоход тусалсан; одоо энэ өдрийг инээж дурсдаг.' },
  ],
  51: [
    { question: 'Рекс өгүүлэгчийг хэзээ сэрээдэг вэ?', choices: ['Орой бүр', 'Өглөө бүр', 'Зөвхөн амралтын өдөр'], correctIndex: 1,
      hint: '"weckt mich jeden Morgen" — jeden Morgen.', explanation: '"Mein Hund Rex weckt mich jeden Morgen" — өглөө бүр сэрээдэг, дараа нь цэцэрлэгт зугаалдаг.' },
    { question: 'Үдээс хойш тэд юу хийдэг вэ?', choices: ['Бөмбөгөөр тоглодог', 'Унтдаг', 'Гүйдэг'], correctIndex: 0,
      hint: '"Am Nachmittag spielen wir mit dem Ball".', explanation: '"spielen wir mit dem Ball" — бөмбөгөөр тоглодог. Рекс бол хамгийн сайн найз нь.' },
  ],
  52: [
    { question: 'Тэр банкинд юу хийхээр очсон бэ?', choices: ['Зээл авах', 'Мөнгө шилжүүлэх', 'Данс нээх'], correctIndex: 2,
      hint: '"weil ich ein Konto eröffnen möchte" — Konto eröffnen.', explanation: '"ein Konto eröffnen" — данс нээх гэсэн хэллэг.' },
    { question: 'Данс нээхэд юу хэрэгтэй вэ?', choices: ['Паспорт ба хаяг', 'Зураг ба гарын үсэг', 'Ажлын гэрээ'], correctIndex: 0,
      hint: '"Ich brauche meinen Pass und eine Adresse".', explanation: 'Pass (паспорт) + Adresse (хаяг) — 10 минутын дараа бүх зүйл бэлэн болдог.' },
  ],
};

export const LISTENING_QUESTIONS: Record<number, QuizQuestion[]> = {
  1: [
    { question: 'Цаг хэд болж байна вэ?', choices: ['8:15', '7:15', '8:45'], correctIndex: 0,
      hint: '"Viertel nach acht" = 8 цагаас 15 минут өнгөрсөн.', explanation: '"Es ist Viertel nach acht" — Viertel nach нь "15 минут өнгөрсөн", тиймээс 8:15.' },
    { question: 'Асуусан хүн юу гэж эхэлсэн бэ?', choices: ['Hallo', 'Entschuldigung', 'Guten Morgen'], correctIndex: 1,
      hint: 'Танихгүй хүнээс юм асуухдаа ямар үг хэрэглэдэг вэ?', explanation: '"Entschuldigung, wie spät ist es?" — Entschuldigung (уучлаарай) нь эелдэг хандлага.' },
  ],
  2: [
    { question: 'Тэд хэдэн цагт уулзах вэ?', choices: ['8 цагт', '16 цагт', '6 цагт'], correctIndex: 2,
      hint: '"um sechs Uhr" — sechs = 6.', explanation: '"Wir treffen uns morgen um sechs Uhr" — маргааш 6 цагт.' },
    { question: 'Тэд хаана уулзах вэ?', choices: ['Кино театрын урд', 'Кафед', 'Буудал дээр'], correctIndex: 0,
      hint: '"vor dem Kino" — vor нь "урд".', explanation: '"vor dem Kino" — кино театрын урд талд уулзана.' },
  ],
  3: [
    { question: 'Тэр хэдэн кило алим авч байна вэ?', choices: ['Хоёр кило', 'Нэг кило', 'Хагас кило'], correctIndex: 1,
      hint: '"ein Kilo Äpfel" — ein = нэг.', explanation: '"ein Kilo Äpfel und zwei Bananen" — нэг кило алим, хоёр ширхэг гадил.' },
    { question: '"Ich hätte gern …" гэдэг хэллэг юу илэрхийлдэг вэ?', choices: ['Уурласан шаардлага', 'Эелдэг хүсэлт', 'Асуулт'], correctIndex: 1,
      hint: 'Дэлгүүрт юм авахдаа хэрэглэдэг хамгийн эелдэг хэлбэр.', explanation: '"Ich hätte gern" нь Konjunktiv II хэлбэр — "Надад … өгөөч" гэсэн эелдэг хүсэлт.' },
  ],
  4: [
    { question: 'Зарлал хэнд хандсан бэ?', choices: ['Берлин рүү зорчигчдод', 'Франкфурт руу зорчигчдод', 'Мюнхен рүү зорчигчдод'], correctIndex: 1,
      hint: '"für die Reisenden nach Frankfurt".', explanation: '"Information für die Reisenden nach Frankfurt" — Франкфурт руу явах зорчигчдод зориулсан мэдээлэл.' },
    { question: 'Галт тэрэг хэдэн минут хоцорч байна вэ?', choices: ['20 минут', '5 минут', '10 минут'], correctIndex: 2,
      hint: '"zehn Minuten Verspätung" — zehn = ?', explanation: '"hat heute zehn Minuten Verspätung" — Verspätung нь хоцролт, 10 минут.' },
  ],
  5: [
    { question: 'Зочин юу захиалж байна вэ?', choices: ['Кофе ба нэг аяга ус', 'Цай ба бялуу', 'Зөвхөн ус'], correctIndex: 0,
      hint: '"Einen Kaffee, bitte. Und ein Glas Wasser."', explanation: 'Кофе + нэг аяга ус — хоёуланг нь захиалсан.' },
    { question: 'Зөөгч юу гэж асуусан бэ?', choices: ['Юу идэхийг', 'Юу уухыг', 'Төлбөрөө хэрхэн төлөхийг'], correctIndex: 1,
      hint: '"Was möchten Sie trinken?" — trinken гэдэг үйл үг.', explanation: '"Was möchten Sie trinken?" — юу уухыг асуусан (essen биш trinken).' },
  ],
  6: [
    { question: 'Шуудан хаана байна вэ?', choices: ['Дэлгүүрийн хажууд', 'Сургуулийн урд', 'Банкны хажууд'], correctIndex: 2,
      hint: '"Die Post ist neben der Bank" — neben нь "хажууд".', explanation: '"neben der Bank" — банкны хажууд байрладаг.' },
    { question: 'Яаж очих замыг зааж өгсөн бэ?', choices: ['Чигээрээ яваад зүүн тийш', 'Чигээрээ яваад баруун тийш', 'Буцаж яваад зүүн тийш'], correctIndex: 0,
      hint: '"geradeaus und dann links" — links = зүүн.', explanation: '"Gehen Sie geradeaus und dann links" — чигээрээ яваад зүүн тийш эргэнэ.' },
  ],
  7: [
    { question: 'Цаг агаар ямар байна вэ?', choices: ['Нартай, халуун', 'Бороотой, хүйтэн', 'Цастай'], correctIndex: 1,
      hint: '"Es regnet und es ist kalt".', explanation: '"Es regnet" (бороо орж байна) + "es ist kalt" (хүйтэн).' },
    { question: 'Юу авч явахыг зөвлөсөн бэ?', choices: ['Малгай', 'Бээлий', 'Шүхэр'], correctIndex: 2,
      hint: '"Nimm einen Regenschirm mit!" — Regen (бороо) + Schirm.', explanation: '"Regenschirm" — борооны шүхэр; mitnehmen нь авч явах.' },
  ],
  8: [
    { question: 'Дэлгүүр хэдэн цагт хаагдах вэ?', choices: ['22 цагт', '20 цагт', '18 цагт'], correctIndex: 1,
      hint: '"um zwanzig Uhr" — zwanzig = 20.', explanation: '"schließt heute um zwanzig Uhr" — 20:00 цагт хаагдана. Германд цагийг 24 цагийн системээр зарладаг.' },
    { question: 'Энэ зарлал хаана сонсогдох вэ?', choices: ['Супермаркетад', 'Галт тэрэгний буудалд', 'Нисэх буудалд'], correctIndex: 0,
      hint: '"Liebe Kunden, unser Supermarkt …" — Kunden гэдэг нь үйлчлүүлэгчид.', explanation: '"unser Supermarkt schließt" — супермаркетын дотоод зарлал, үйлчлүүлэгчдэд хандсан.' },
  ],
  9: [
    { question: 'Юлиа хаанаас ирсэн бэ?', choices: ['Германаас', 'Швейцариас', 'Австриас'], correctIndex: 2,
      hint: '"Ich komme aus Österreich" — Österreich аль улс вэ?', explanation: '"aus Österreich" — Австри улсаас ирсэн.' },
    { question: 'Юлиагийн мэргэжил юу вэ?', choices: ['Багш', 'Эмч', 'Худалдагч'], correctIndex: 0,
      hint: '"arbeite als Lehrerin" — Lehrerin.', explanation: '"als Lehrerin" — багшаар ажилладаг (Lehrerin нь эмэгтэй багш).' },
  ],
  10: [
    { question: 'Хэн залгасан бэ?', choices: ['Эмч Майер', 'Багш Майер', 'Хөрш Майер'], correctIndex: 0,
      hint: '"hier ist Doktor Meyer" — Doktor.', explanation: '"Doktor Meyer" — эмчийн цаг товлох тухай хариулагчийн бичлэг.' },
    { question: 'Цаг хэзээ вэ?', choices: ['Мягмар гарагт 10 цагт', 'Лхагва гарагт 10 цагт', 'Лхагва гарагт 2 цагт'], correctIndex: 1,
      hint: '"am Mittwoch um zehn Uhr" — Mittwoch аль гараг вэ?', explanation: '"am Mittwoch um zehn Uhr" — Mittwoch нь Лхагва (долоо хоногийн дунд өдөр).' },
  ],
  11: [
    { question: 'Тэр эхлээд юу авах вэ?', choices: ['Салат', 'Тахиа', 'Шөл'], correctIndex: 2,
      hint: '"Ich nehme die Suppe und danach …" — эхний хоол.', explanation: '"die Suppe und danach das Hähnchen" — эхлээд шөл, дараа нь гол хоол.' },
    { question: 'Гол хоолонд нь юу дагалдах вэ?', choices: ['Будаа', 'Төмс', 'Гоймон'], correctIndex: 0,
      hint: '"das Hähnchen mit Reis" — Reis гэж юу вэ?', explanation: '"mit Reis" — Reis нь будаа (цагаан будаа).' },
  ],
  12: [
    { question: 'Тэр хэдэн ах дүүтэй вэ?', choices: ['Гурван', 'Хоёр', 'Нэг'], correctIndex: 1,
      hint: '"zwei Geschwister" — Geschwister нь ах эгч дүүсийн нийт нэр.', explanation: '"Ich habe zwei Geschwister: einen Bruder und eine Schwester" — нэг ах, нэг эгч/дүү гэсэн хоёр.' },
    { question: 'Хэн нь ахмад вэ?', choices: ['Ах нь', 'Эгч нь', 'Өгүүлэгч өөрөө'], correctIndex: 0,
      hint: '"Mein Bruder ist älter" — älter нь alt-ын харьцуулсан зэрэг.', explanation: '"Mein Bruder ist älter" — ах нь түүнээс ах (ахмад).' },
  ],
  13: [
    { question: 'Зорчигчид аль гарц руу явах ёстой вэ?', choices: ['5-р гарц', '13-р гарц', '3-р гарц'], correctIndex: 2,
      hint: '"zum Gate drei" — drei = 3.', explanation: '"gehen Sie jetzt zum Gate drei" — 3-р гарц (Gate) руу.' },
    { question: 'Нислэг хаашаа явах вэ?', choices: ['Вена руу', 'Берлин рүү', 'Цюрих рүү'], correctIndex: 0,
      hint: '"des Fluges nach Wien" — Wien аль хот вэ?', explanation: '"Passagiere des Fluges nach Wien" — Вена (Австрийн нийслэл) рүү нисэх зорчигчид.' },
  ],
  14: [
    { question: 'Амралтын өдөр тэр юу хийдэг вэ?', choices: ['Хөлбөмбөг тоглодог', 'Теннис тоглодог', 'Усанд сэлдэг'], correctIndex: 1,
      hint: '"Am Wochenende spiele ich Tennis".', explanation: '"spiele ich Tennis" — теннис тоглодог.' },
    { question: 'Орой тэр юу хийх дуртай вэ?', choices: ['Зурагт үзэх', 'Хоол хийх', 'Ном унших'], correctIndex: 2,
      hint: '"am Abend lese ich gern" — lesen.', explanation: '"am Abend lese ich gern" — орой ном унших дуртай.' },
  ],
  15: [
    { question: 'Тэр ямар өрөө захиалсан бэ?', choices: ['Нэг хүний өрөө', 'Хоёр хүний өрөө', 'Люкс өрөө'], correctIndex: 0,
      hint: '"ein Einzelzimmer" — Einzel гэдэг нь дан/ганц.', explanation: '"Einzelzimmer" — нэг хүний өрөө (Doppelzimmer бол хоёр хүнийх).' },
    { question: 'Хэдэн шөнө байх вэ?', choices: ['Нэг шөнө', 'Гурван шөнө', 'Хоёр шөнө'], correctIndex: 2,
      hint: '"für zwei Nächte" — Nächte нь Nacht-ын олон тоо.', explanation: '"für zwei Nächte reserviert" — хоёр шөнийн захиалга.' },
  ],
  16: [
    { question: 'Өвчтөнд юу болсон бэ?', choices: ['Хоолой өвдөж, ханиалгаж байна', 'Толгой өвдөж байна', 'Гэдэс өвдөж байна'], correctIndex: 0,
      hint: '"Halsschmerzen und Husten" — Hals (хоолой) + Husten (ханиалга).', explanation: '"Ich habe Halsschmerzen und Husten" — хоолойн өвчин + ханиалга.' },
    { question: '"Was fehlt Ihnen?" гэж эмч юуг асууж байна вэ?', choices: ['Нэрийг тань', 'Юу нь өвдөж байгааг', 'Даатгалыг тань'], correctIndex: 1,
      hint: 'Эмчийн өрөөнд орохоор хамгийн түрүүнд асуудаг асуулт.', explanation: '"Was fehlt Ihnen?" нь шууд орчуулбал "Танд юу дутаж байна?" — өвчтөний зовиурыг асуудаг хэллэг.' },
  ],
  17: [
    { question: 'Тэр ямар тийз авсан бэ?', choices: ['Очоод буцах', 'Сарын тийз', 'Зөвхөн нэг тал'], correctIndex: 2,
      hint: '"Nein, nur einfach" — einfach нь нэг талын тийз.', explanation: '"Hin und zurück? — Nein, nur einfach" — очоод буцахаас татгалзаж, нэг талын тийз авсан.' },
    { question: '"Hin und zurück" гэж юу гэсэн үг вэ?', choices: ['Очоод буцах', 'Нэг тал', 'Хоёр хүн'], correctIndex: 0,
      hint: 'hin = очих чиглэл, zurück = буцах чиглэл.', explanation: '"hin und zurück" нь очих + буцах хоёр талын тийз гэсэн тогтсон хэллэг.' },
  ],
  18: [
    { question: 'Ямар өдөр, цагийг санал болгосон бэ?', choices: ['Пүрэв 9 цагт', 'Баасан 9 цагт', 'Баасан 10 цагт'], correctIndex: 1,
      hint: '"am Freitag um neun" — Freitag аль гараг вэ?', explanation: '"Geht es am Freitag um neun?" — Баасан гарагийн 9 цагийг санал болгосон.' },
    { question: '"Geht es am …?" гэдэг хэллэг юу гэсэн утгатай вэ?', choices: ['Хаашаа явах вэ?', '… болох уу? (тохирох уу?)', 'Хэн ирэх вэ?'], correctIndex: 1,
      hint: 'Цаг тохирохдоо хэрэглэдэг асуулт.', explanation: '"Geht es am Freitag?" нь "Баасан гараг танд тохирох уу?" — цаг товлохдоо өргөн хэрэглэдэг.' },
  ],
  19: [
    { question: 'Орон сууц хэддүгээр давхарт вэ?', choices: ['Гуравдугаар', 'Хоёрдугаар', 'Дөрөвдүгээр'], correctIndex: 0,
      hint: '"im dritten Stock" — dritt = гурав дахь.', explanation: '"im dritten Stock" — 3-р давхарт; гурван өрөө, том тагттай.' },
    { question: 'Орон сууц хэдэн өрөөтэй вэ?', choices: ['Хоёр', 'Дөрвөн', 'Гурван'], correctIndex: 2,
      hint: '"drei Zimmer" — drei = ?', explanation: '"hat drei Zimmer und einen großen Balkon" — гурван өрөө + том тагт.' },
  ],
  20: [
    { question: 'Өглөөний цайнд тэр юу иддэг вэ?', choices: ['Өндөг ба цөцгийн тостой талх', 'Зөвхөн жимс', 'Будаа'], correctIndex: 0,
      hint: '"ein Ei, Brot mit Butter" — Ei (өндөг), Butter (цөцгийн тос).', explanation: '"esse ich ein Ei, Brot mit Butter" — өндөг + цөцгийн тостой талх.' },
    { question: 'Тэр юу уудаг вэ?', choices: ['Кофе', 'Сүү', 'Жүржийн шүүс'], correctIndex: 2,
      hint: '"trinke Orangensaft" — Orange + Saft.', explanation: '"Orangensaft" — жүржийн шүүс (Orange = жүрж, Saft = шүүс).' },
  ],
  21: [
    { question: 'Хямдрал хаана байгаа вэ?', choices: ['Нэгдүгээр давхарт', 'Хоёрдугаар давхарт', 'Зоорийн давхарт'], correctIndex: 1,
      hint: '"Im zweiten Stock" — zweit = хоёр дахь.', explanation: '"Im zweiten Stock finden Sie …" — 2-р давхарт.' },
    { question: 'Юу хагас үнэтэй байгаа вэ?', choices: ['Зуны даашинз', 'Гутал', 'Өвлийн хүрэм'], correctIndex: 2,
      hint: '"alle Winterjacken zum halben Preis" — Winterjacke.', explanation: '"alle Winterjacken zum halben Preis" — бүх өвлийн хүрэм 50% хямдралтай.' },
  ],
  22: [
    { question: 'Аль зам дээр түгжрэл байна вэ?', choices: ['A1 хурдны зам', 'A5 хурдны зам', 'B1 зам'], correctIndex: 0,
      hint: '"Auf der Autobahn A1".', explanation: '"Auf der Autobahn A1 gibt es einen Stau" — A1 хурдны зам дээр.' },
    { question: 'Түгжрэл хэдэн километр вэ?', choices: ['Хоёр км', 'Таван км', 'Арван км'], correctIndex: 1,
      hint: '"von fünf Kilometern" — fünf = ?', explanation: '"einen Stau von fünf Kilometern" — 5 км түгжрэл; удаан жолоодохыг сануулсан.' },
  ],
  23: [
    { question: 'Ноён Кляйн одоо хаана байна вэ?', choices: ['Хурал дээр', 'Амралтанд', 'Одоо байхгүй (алга)'], correctIndex: 2,
      hint: '"ist gerade nicht da" — nicht da.', explanation: '"Herr Klein ist gerade nicht da" — яг одоо байхгүй гэсэн; хаана байгааг хэлээгүй.' },
    { question: '"Kann ich etwas ausrichten?" гэж юу санал болгож байна вэ?', choices: ['Зурвас дамжуулахыг', 'Дахин залгахыг', 'Хүлээхийг'], correctIndex: 0,
      hint: 'ausrichten гэдэг нь хэн нэгэнд үг дамжуулах.', explanation: '"etwas ausrichten" — таны хэлэхийг хүссэн зүйлийг ноён Кляйнд дамжуулж өгөхийг санал болгож байна.' },
  ],
  24: [
    { question: 'Тэд зун хаашаа нисэх вэ?', choices: ['Итали руу', 'Испани руу', 'Грек рүү'], correctIndex: 1,
      hint: '"fliegen wir nach Spanien" — Spanien.', explanation: '"Im Sommer fliegen wir nach Spanien" — Испани руу ниснэ.' },
    { question: 'Тэд хаана, хэр удаан байх вэ?', choices: ['Далайн эрэг дээр хоёр долоо хоног', 'Ууланд нэг долоо хоног', 'Хотод гурван өдөр'], correctIndex: 0,
      hint: '"zwei Wochen am Strand" — Strand нь далайн эрэг.', explanation: '"Wir bleiben zwei Wochen am Strand" — далайн эрэг дээр хоёр долоо хоног.' },
  ],
  25: [
    { question: 'Тэр ямар ажил хийж байсан бэ?', choices: ['Жолооч', 'Тогооч', 'Худалдагч'], correctIndex: 2,
      hint: '"als Verkäufer gearbeitet" — Verkäufer.', explanation: '"Ich habe drei Jahre als Verkäufer gearbeitet" — худалдагчаар ажилласан.' },
    { question: 'Энэ яриа ямар нөхцөлд болж байна вэ?', choices: ['Ажлын ярилцлагад', 'Дэлгүүрт', 'Найзуудын уулзалтад'], correctIndex: 0,
      hint: '"Erzählen Sie etwas über sich" — энэ асуултыг хэн асуудаг вэ?', explanation: '"Erzählen Sie etwas über sich" (өөрийнхөө тухай ярина уу) нь ажлын ярилцлагын ердийн эхлэл.' },
  ],
  26: [
    { question: 'Курс хэзээ эхлэх вэ?', choices: ['Дараа долоо хоногийн Даваад', 'Энэ Баасанд', 'Дараа сард'], correctIndex: 0,
      hint: '"nächste Woche am Montag".', explanation: '"Der Kurs beginnt nächste Woche am Montag" — дараа долоо хоногийн Даваа гарагт.' },
    { question: 'Юу авч ирэх ёстой вэ?', choices: ['Дэвтэр', 'Толь бичиг', 'Зурагт үнэмлэх'], correctIndex: 1,
      hint: '"Bringen Sie ein Wörterbuch mit" — Wörter + Buch.', explanation: '"ein Wörterbuch" — толь бичиг (Wörter = үгс, Buch = ном).' },
  ],
  27: [
    { question: 'Хэдэн хүний ширээ захиалж байна вэ?', choices: ['Хоёр', 'Зургаан', 'Дөрвөн'], correctIndex: 2,
      hint: '"für vier Personen" — vier = ?', explanation: '"einen Tisch für vier Personen" — дөрвөн хүний ширээ.' },
    { question: 'Хэзээний захиалга вэ?', choices: ['Өнөө орой 8 цагт', 'Маргааш үдэд', 'Бямба гарагт'], correctIndex: 0,
      hint: '"für heute Abend um acht".', explanation: '"für heute Abend um acht" — өнөө орой 20:00 цагт.' },
  ],
  28: [
    { question: 'Маргааш өдөртөө цаг агаар ямар байх вэ?', choices: ['Бороотой', 'Нартай, 20 хэм хүртэл', 'Манантай'], correctIndex: 1,
      hint: '"sonnig mit Temperaturen bis zwanzig Grad".', explanation: '"Morgen wird es sonnig … bis zwanzig Grad" — нартай, 20 хэм хүртэл дулаан.' },
    { question: 'Орой юу болж магадгүй вэ?', choices: ['Цас орж магадгүй', 'Салхи гарч магадгүй', 'Аадар бороо орж магадгүй'], correctIndex: 2,
      hint: '"Am Abend kann es gewittern" — Gewitter нь аадар.', explanation: '"kann es gewittern" — аадар бороо, аянга цахилгаантай байж магадгүй.' },
  ],
  29: [
    { question: 'Эмийг өдөрт хэдэн удаа уух вэ?', choices: ['Гурван удаа', 'Нэг удаа', 'Хоёр удаа'], correctIndex: 0,
      hint: '"dreimal am Tag" — dreimal.', explanation: '"Nehmen Sie diese Tabletten dreimal am Tag" — өдөрт гурван удаа.' },
    { question: 'Эмийг хэзээ уух ёстой вэ?', choices: ['Хоолны өмнө', 'Хоолны дараа', 'Унтахын өмнө'], correctIndex: 1,
      hint: '"nach dem Essen" — nach нь "дараа".', explanation: '"nach dem Essen" — хоолны дараа (vor dem Essen бол өмнө нь).' },
  ],
  30: [
    { question: 'Тэр мөнгөө хэрхэн авахаар шийдсэн бэ?', choices: ['Бэлнээр', 'Чекээр', 'Дансаар'], correctIndex: 2,
      hint: '"Auf das Konto, bitte" — Konto нь данс.', explanation: '"Auf das Konto, bitte" — дансандаа хийлгэхээр сонгосон (in bar = бэлнээр).' },
    { question: '"in bar" гэж юу гэсэн үг вэ?', choices: ['Бэлэн мөнгөөр', 'Картаар', 'Зээлээр'], correctIndex: 0,
      hint: 'Bar нь баар биш — төлбөрийн хэлбэр!', explanation: '"in bar" нь бэлэн мөнгөөр гэсэн тогтсон хэллэг — банк, дэлгүүрт байнга сонсогдоно.' },
  ],
  31: [
    { question: 'Бямба гарагт юу болох вэ?', choices: ['Төрсөн өдөр', 'Шарсан махны үдэшлэг (Grillparty)', 'Хурим'], correctIndex: 1,
      hint: '"machen am Samstag eine Grillparty".', explanation: '"wir machen am Samstag eine Grillparty" — гадаа шарсан махны үдэшлэг.' },
    { question: 'Анна юу авч ирэх ёстой вэ?', choices: ['Ундаа', 'Бялуу', 'Салат'], correctIndex: 2,
      hint: '"Bring bitte einen Salat mit" — mitbringen.', explanation: '"Bring bitte einen Salat mit" — салат авчрахыг хүссэн.' },
  ],
  32: [
    { question: 'Дараагийн буудал юу вэ?', choices: ['Төв вокзал (Hauptbahnhof)', 'Зах', 'Их сургууль'], correctIndex: 0,
      hint: '"Nächster Halt: Hauptbahnhof" — Haupt + Bahnhof.', explanation: '"Nächster Halt: Hauptbahnhof" — төв (Haupt) вокзал.' },
    { question: 'Юунд анхаарал хандуулахыг сануулсан бэ?', choices: ['Цүнхээ мартахгүй байх', 'Галт тэрэг ба тавцангийн хоорондох завсарт', 'Тийзээ шалгуулах'], correctIndex: 1,
      hint: '"die Lücke zwischen Zug und Bahnsteig" — Lücke нь завсар.', explanation: '"Bitte beachten Sie die Lücke" — буухдаа завсар руу гишгэхээс болгоомжлохыг сануулдаг стандарт зарлал.' },
  ],
  33: [
    { question: 'Ажлын өдрүүдэд заал хэдэн цаг хүртэл нээлттэй вэ?', choices: ['20 цаг хүртэл', '18 цаг хүртэл', '22 цаг хүртэл'], correctIndex: 2,
      hint: '"von Montag bis Freitag bis 22 Uhr".', explanation: 'Даваа-Баасанд 22 цаг хүртэл, амралтын өдөр 18 цаг хүртэл — хоёр цагийг андуурахгүй байх нь чухал.' },
    { question: 'Амралтын өдөр хэдэн цаг хүртэл вэ?', choices: ['18 цаг хүртэл', '22 цаг хүртэл', '16 цаг хүртэл'], correctIndex: 0,
      hint: '"am Wochenende bis 18 Uhr".', explanation: '"am Wochenende bis 18 Uhr" — амралтын өдрүүдэд эрт хаадаг.' },
  ],
  34: [
    { question: 'Хэдэн цагийн үзүүлбэрт тийз авсан бэ?', choices: ['18 цагийн', '20 цагийн', '22 цагийн'], correctIndex: 1,
      hint: '"für die Vorstellung um zwanzig Uhr".', explanation: '"um zwanzig Uhr" — 20:00 цагийн үзүүлбэр.' },
    { question: 'Суудал нь хаана вэ?', choices: ['10-р эгнээ, 5 ба 6-р суудал', '5-р эгнээ, 10 ба 11-р суудал', '6-р эгнээ, 5 ба 10-р суудал'], correctIndex: 0,
      hint: '"Reihe zehn, Plätze fünf und sechs" — Reihe нь эгнээ.', explanation: '"Reihe zehn, Plätze fünf und sechs" — 10-р эгнээний 5, 6-р суудал.' },
  ],
  35: [
    { question: 'Тэр яагаад ажилдаа ирж чадахгүй вэ?', choices: ['Машин нь эвдэрсэн', 'Амралтанд байгаа', 'Өвчтэй байгаа'], correctIndex: 2,
      hint: '"ich bin heute krank" — krank.', explanation: '"ich bin heute krank und kann nicht zur Arbeit kommen" — өвчтэй тул ирж чадахгүй.' },
    { question: 'Энэ дуудлагыг хэзээ хийж байна вэ?', choices: ['Өглөө', 'Үдэд', 'Орой'], correctIndex: 0,
      hint: 'Мэндчилгээг анхаар: "Guten Morgen".', explanation: '"Guten Morgen" гэж эхэлсэн — ажил эхлэхээс өмнө өглөө нь мэдэгдэж байна (ёс зүйн хувьд зөв).' },
  ],
  36: [
    { question: 'Тэр гутлаа яагаад солих гэж байна вэ?', choices: ['Хэт жижиг учраас', 'Хэт том учраас', 'Эвдэрсэн учраас'], correctIndex: 0,
      hint: '"Sie sind leider zu klein" — zu klein.', explanation: '"zu klein" — хэмжээ нь жижигдсэн тул солиулахаар авчирсан.' },
    { question: '"umtauschen" гэдэг үг юу гэсэн утгатай вэ?', choices: ['Буцааж өгөх', 'Солих', 'Засуулах'], correctIndex: 1,
      hint: 'um- угтвар нь өөрчлөлт заадаг (umziehen = нүүх).', explanation: '"umtauschen" нь барааг өөр хэмжээ/өнгөөр солих; zurückgeben бол буцааж өгөх.' },
  ],
  37: [
    { question: 'Эцэг эхийн хурал хэзээ болох вэ?', choices: ['Пүрэв гарагт 19 цагт', 'Мягмар гарагт 18 цагт', 'Баасан гарагт 19 цагт'], correctIndex: 0,
      hint: '"am Donnerstag um neunzehn Uhr" — Donnerstag.', explanation: '"am Donnerstag um neunzehn Uhr" — Пүрэв гараг, 19:00 цагт.' },
    { question: 'Хурал хаана болох вэ?', choices: ['Спорт зааланд', 'Ангид', 'Хурлын танхимд (Aula)'], correctIndex: 2,
      hint: '"in der Aula statt" — Aula гэдэг нь сургуулийн том танхим.', explanation: '"findet … in der Aula statt" — stattfinden (болох) + Aula (хурлын танхим).' },
  ],
  38: [
    { question: 'Галт тэрэг хэдэн цагт хөдлөх вэ?', choices: ['14:00-д', '14:20-д', '15:20-д'], correctIndex: 1,
      hint: '"um 14:20" — цагийг яг сонс.', explanation: '"fährt um 14:20" — 14 цаг 20 минутад Мюнхен рүү хөдөлнө.' },
    { question: 'Хэддүгээр замаас хөдлөх вэ?', choices: ['9-р зам', '5-р зам', '7-р зам'], correctIndex: 2,
      hint: '"von Gleis sieben" — sieben = ?', explanation: '"von Gleis sieben" — 7-р зам (Gleis) — буудлын зарлалд байнга сонсогддог үг.' },
  ],
  39: [
    { question: 'Юу ажиллахгүй байна вэ?', choices: ['Халаалт', 'Цахилгаан', 'Усны кран'], correctIndex: 0,
      hint: '"Die Heizung funktioniert nicht" — Heizung.', explanation: '"Die Heizung funktioniert nicht" — халаалт ажиллахгүй байна.' },
    { question: 'Засварчинг хэзээ ирэхийг хүсэж байна вэ?', choices: ['Өнөөдөр орой', 'Маргааш үдээс өмнө', 'Дараа долоо хоногт'], correctIndex: 1,
      hint: '"morgen Vormittag" — Vormittag нь үдээс өмнөх цаг.', explanation: '"Können Sie morgen Vormittag kommen?" — маргааш үдээс өмнө ирж чадах эсэхийг асуусан.' },
  ],
  40: [
    { question: 'Гүзээлзгэнэ ямар үнэтэй вэ?', choices: ['Кило нь 3 евро', 'Кило нь 2 евро', 'Ширхэг нь 3 евро'], correctIndex: 0,
      hint: '"drei Euro das Kilo".', explanation: '"kosten heute drei Euro das Kilo" — нэг кило нь 3 евро.' },
    { question: 'Худалдагч гүзээлзгэнийг хэрхэн магтсан бэ?', choices: ['Хямд гэж', 'Маш шинэхэн гэж', 'Том гэж'], correctIndex: 1,
      hint: '"Sie sind ganz frisch" — frisch.', explanation: '"ganz frisch" — маш шинэхэн гэж онцолсон.' },
  ],
  41: [
    { question: 'Хэзээнээс шинэ чиглэл нэвтрэх вэ?', choices: ['Өнөөдрөөс', 'Дараа сараас', 'Дараа долоо хоногоос'], correctIndex: 2,
      hint: '"ab nächster Woche" — ab нь "-аас эхлэн".', explanation: '"ab nächster Woche" — дараа долоо хоногоос эхлэн автобусны шинэ чиглэл ажиллана.' },
    { question: 'Шинэ чиглэл юуг юутай холбох вэ?', choices: ['Вокзалыг эмнэлэгтэй', 'Сургуулийг захтай', 'Нисэх буудлыг төвтэй'], correctIndex: 0,
      hint: '"verbindet den Bahnhof mit dem Krankenhaus".', explanation: '"verbindet den Bahnhof mit dem Krankenhaus" — вокзал ба эмнэлгийн хооронд явна.' },
  ],
  42: [
    { question: 'Төслийг хэзээ дуусгах ёстой вэ?', choices: ['Баасан гарагт', 'Сарын эцэс гэхэд', 'Дараа жил'], correctIndex: 1,
      hint: '"bis Ende des Monats" — Ende des Monats.', explanation: '"das Projekt bis Ende des Monats abschließen" — сарын эцэс гэхэд дуусгана.' },
    { question: 'Тайланг хэзээ илгээх ёстой вэ?', choices: ['Сарын эцэст', 'Даваа гараг хүртэл', 'Баасан гараг хүртэл'], correctIndex: 2,
      hint: '"bis Freitag" — хоёр өөр хугацааг бүү хольж хутга!', explanation: '"Ihre Berichte bis Freitag" — тайлан Баасан хүртэл, харин төсөл өөрөө сарын эцэс хүртэл.' },
  ],
  43: [
    { question: 'Шалгалттай юу болсон бэ?', choices: ['Цуцлагдсан', 'Эрт болсон', 'Хойшилсон'], correctIndex: 2,
      hint: '"wurde verschoben" — verschieben нь хойшлуулах.', explanation: '"Die Prüfung wurde verschoben" — Passiv хэлбэрээр "шалгалт хойшлогдсон".' },
    { question: 'Шалгалт одоо хэзээ болох вэ?', choices: ['Хоёр долоо хоногийн дараа', 'Маргааш', 'Нэг сарын дараа'], correctIndex: 0,
      hint: '"erst in zwei Wochen" — in + хугацаа нь "дараа".', explanation: '"findet jetzt erst in zwei Wochen statt" — хоёр долоо хоногийн дараа л болно.' },
  ],
  44: [
    { question: 'Тэр үсээ хэрхэн засуулахыг хүсэж байна вэ?', choices: ['Маш богино', 'Зөвхөн үзүүрийг нь', 'Будуулах'], correctIndex: 1,
      hint: '"Nur die Spitzen, bitte" — Spitzen нь үзүүр.', explanation: '"nicht zu kurz. Nur die Spitzen" — хэт богино биш, зөвхөн үзүүрийг нь засна.' },
    { question: '"schneiden lassen" гэдэг хэллэг юуг илэрхийлдэг вэ?', choices: ['Өөрөө хайчлах', 'Бусдаар хийлгэх', 'Хайчлахаас татгалзах'], correctIndex: 1,
      hint: 'lassen + үйл үг = өөрөө биш, хэн нэгнээр хийлгэх.', explanation: '"die Haare schneiden lassen" — үсчингээр засуулах; lassen нь үйлчилгээ авахыг заадаг чухал бүтэц.' },
  ],
  45: [
    { question: 'Төхөөрөмжид ямар асуудал байна вэ?', choices: ['Ажиллахгүй байгаа', 'Хэт үнэтэй', 'Буруу өнгөтэй'], correctIndex: 0,
      hint: '"es funktioniert nicht".', explanation: '"aber es funktioniert nicht" — өчигдөр авсан ч ажиллахгүй байна.' },
    { question: 'Үйлчлүүлэгч юу хүсэж байна вэ?', choices: ['Засуулахыг', 'Шинээр солихыг', 'Мөнгөө буцааж авахыг'], correctIndex: 2,
      hint: '"Ich möchte mein Geld zurück".', explanation: '"mein Geld zurück" — засвар, солилт биш мөнгөө буцаахыг шаардаж байна.' },
  ],
  46: [
    { question: 'Яагаад эрт захиалахыг зөвлөсөн бэ?', choices: ['8-р сард нислэгүүд дүүрдэг учраас', 'Үнэ өсдөг учраас', 'Виз удаан гардаг учраас'], correctIndex: 0,
      hint: '"denn im August sind die Flüge oft ausgebucht" — ausgebucht.', explanation: '"ausgebucht" — бүх суудал захиалагдаж дууссан гэсэн үг; 8-р сард байнга тохиолддог.' },
    { question: 'Энэ яриа хаана болж байна вэ?', choices: ['Нисэх буудалд', 'Аялалын агентлагт', 'Зочид буудалд'], correctIndex: 1,
      hint: '"Für diese Reise empfehle ich Ihnen …" — хэн ингэж зөвлөдөг вэ?', explanation: 'Аяллыг санал болгож, захиалга зөвлөж буй нь аялалын агентлагийн ажилтны яриа.' },
  ],
  47: [
    { question: 'Шинжилгээний үр дүн ямар байна вэ?', choices: ['Сайн байна', 'Муу байна', 'Тодорхойгүй байна'], correctIndex: 0,
      hint: '"Die Ergebnisse sehen gut aus".', explanation: '"sehen gut aus" — үр дүн сайн харагдаж байна.' },
    { question: 'Эмч юу зөвлөсөн бэ?', choices: ['Эм уух, амрах', 'Илүү унтах', 'Давс багасгаж, спорт хийх'], correctIndex: 2,
      hint: '"weniger Salz … mehr Sport".', explanation: '"weniger Salz essen und mehr Sport treiben" — давс багасгаж, хөдөлгөөн нэмэх.' },
  ],
  48: [
    { question: 'Түрээс хэд вэ, юу багтсан бэ?', choices: ['800 евро, халаалт орсон', '800 евро, халаалт ороогүй', '600 евро, бүгд орсон'], correctIndex: 0,
      hint: '"800 Euro warm, inklusive Heizung" — warm гэдэг нь халаалттай үнэ.', explanation: '"warm" түрээс гэдэг нь халаалт зэрэг нэмэлт зардал орсон үнэ; "kalt" бол ороогүй.' },
    { question: 'Орон сууцыг хэрхэн дүрсэлсэн бэ?', choices: ['Том боловч харанхуй', 'Гэрэлтэй, нам гүм', 'Шинэ, тавилгатай'], correctIndex: 1,
      hint: '"hell und ruhig".', explanation: '"Die Wohnung ist hell und ruhig" — гэрэлтэй (hell), нам гүм (ruhig).' },
  ],
  49: [
    { question: 'Сайн дурынхан юу хийх вэ?', choices: ['Хүүхэд харах', 'Хоол хүргэх', 'Өндөр настнуудад худалдан авалтад туслах'], correctIndex: 2,
      hint: '"älteren Menschen beim Einkaufen helfen".', explanation: '"die … beim Einkaufen helfen" — өндөр настнуудын худалдан авалтад туслана.' },
    { question: 'Хэр олон удаа туслах вэ?', choices: ['Долоо хоногт нэг удаа', 'Өдөр бүр', 'Сард нэг удаа'], correctIndex: 0,
      hint: '"einmal pro Woche" — einmal.', explanation: '"einmal pro Woche" — долоо хоногт нэг удаа гэсэн тогтмол давтамж.' },
  ],
  50: [
    { question: 'Эхлээд юу хийхийг зөвлөсөн бэ?', choices: ['Шинэ төхөөрөмж авах', 'Төхөөрөмжийг дахин асаах', 'Дэлгүүрт аваачих'], correctIndex: 1,
      hint: '"Bitte starten Sie das Gerät neu" — neu starten.', explanation: '"starten Sie das Gerät neu" — дахин асаах (restart) нь эхний алхам.' },
    { question: 'Асуудал хэвээр байвал юу болох вэ?', choices: ['Мөнгө буцаана', 'Шинэ төхөөрөмж илгээнэ', 'Техникч илгээнэ'], correctIndex: 2,
      hint: '"Wenn das Problem bleibt, schicken wir einen Techniker".', explanation: '"schicken wir einen Techniker" — техникч (засварчин) илгээнэ гэж амласан.' },
  ],
  51: [
    { question: 'Өнөө шөнө юу болох вэ?', choices: ['Их цас орно', 'Бороо орно', 'Салхи гарна'], correctIndex: 0,
      hint: '"Heute Nacht schneit es stark" — schneien.', explanation: '"schneit es stark" — их хэмжээний цас орно.' },
    { question: 'Цасны улмаас юу болох вэ?', choices: ['Автобус зогсоно', 'Сургуулиуд хаалттай байна', 'Дэлгүүрүүд хаагдана'], correctIndex: 1,
      hint: '"Die Schulen bleiben morgen geschlossen".', explanation: '"bleiben geschlossen" — маргааш сургуулиуд хаалттай хэвээр байна.' },
  ],
  52: [
    { question: 'Тэд хэзээ уулзахаар тохирсон бэ?', choices: ['Ням гарагт 3 цагт', 'Бямба гарагт 3 цагт', 'Ням гарагт 5 цагт'], correctIndex: 0,
      hint: '"am Sonntag … Um drei Uhr".', explanation: '"Treffen wir uns am Sonntag im Park? … Um drei Uhr" — Ням гарагийн 15:00 цагт.' },
    { question: 'Тэд цэцэрлэгийн яг хаана уулзах вэ?', choices: ['Нуурын дэргэд', 'Кафены урд', 'Үүдэнд (орох хаалган дээр)'], correctIndex: 2,
      hint: '"beim Eingang" — Eingang нь орох хаалга.', explanation: '"Um drei Uhr beim Eingang" — цэцэрлэгт хүрээлэнгийн үүдэнд.' },
  ],
};
