// Build frontend/src/c1c2Vocabulary.ts from scripts/c1c2Words.json.
// -----------------------------------------------------------------------------
// For every curated C1/C2 headword we look the Mongolian meaning up in the
// Bolor-toli German→Mongolian dictionary (human-edited, App Store: "Bolor
// dictionary") rather than machine-translating it. Resumable: words already
// present (with a non-empty Mongolian gloss) in the output are not re-fetched.
//
// Usage: npx tsx scripts/generateC1C2.ts
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { lookup, extractMongolian, extractArticle } from './bolorToli';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const IN_FILE = path.resolve(__dirname, 'c1c2Words.json');
const OUT_FILE = path.resolve(__dirname, '../frontend/src/c1c2Vocabulary.ts');

interface Seed {
  german: string;
  article?: 'der' | 'die' | 'das';
  wordClass: 'noun' | 'verb' | 'adjective' | 'adverb';
  level: 'C1' | 'C2';
}

interface Entry extends Seed {
  mongolian: string;
  category: string;
  // Required (possibly empty) on VocabularyWord — same convention as vocabeo.
  exampleGerman: string;
  exampleMongolian: string;
}

const WC_MN: Record<string, string> = {
  noun: 'Нэр үг', verb: 'Үйл үг', adjective: 'Тэмдэг нэр', adverb: 'Дайвар үг',
};

function categoryFor(seed: Seed): string {
  return `${WC_MN[seed.wordClass] ?? 'Үг'} (${seed.level})`;
}

function loadExisting(): Record<string, Entry> {
  if (!fs.existsSync(OUT_FILE)) return {};
  const src = fs.readFileSync(OUT_FILE, 'utf8');
  const m = src.match(/JSON\.parse\(\s*"([\s\S]*?)"\s*\)/);
  if (!m) return {};
  const arr: Entry[] = JSON.parse(JSON.parse(`"${m[1]}"`));
  const map: Record<string, Entry> = {};
  for (const e of arr) map[e.german] = e;
  return map;
}

function save(entries: Entry[]) {
  // Match the vocabeoVocabulary.ts shape: a JSON.parse of a string literal so the
  // huge array doesn't bloat the parsed-source size.
  const json = JSON.stringify(entries);
  const escaped = JSON.stringify(json); // double-encode → safe string literal
  const body =
    `// AUTO-GENERATED by scripts/generateC1C2.ts — do not edit by hand.\n` +
    `// Advanced C1/C2 German vocabulary for the flashcard trainer. Mongolian\n` +
    `// meanings come from the Bolor-toli German→Mongolian dictionary\n` +
    `// (https://bolor-toli.com — App Store: "Bolor dictionary"), not machine\n` +
    `// translation. Regenerate with:  npx tsx scripts/generateC1C2.ts\n` +
    `import { VocabularyWord } from './types';\n\n` +
    `export const C1C2_VOCABULARY: VocabularyWord[] = JSON.parse(\n  ${escaped}\n);\n`;
  fs.writeFileSync(OUT_FILE, body);
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const rawSeeds: Seed[] = JSON.parse(fs.readFileSync(IN_FILE, 'utf8'));
  const seen = new Set<string>();
  const seeds = rawSeeds.filter((s) => {
    const k = s.german.toLowerCase();
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
  const existing = loadExisting();
  const out: Entry[] = [];
  const failures: string[] = [];

  for (const seed of seeds) {
    const prior = existing[seed.german];
    if (prior?.mongolian) {
      out.push({ exampleGerman: '', exampleMongolian: '', ...prior });
      continue;
    }

    let mongolian = '';
    let article = seed.article;
    for (let attempt = 0; attempt < 4 && !mongolian; attempt++) {
      try {
        const resp = await lookup(seed.german);
        mongolian = extractMongolian(resp, seed.german);
        article = article ?? (extractArticle(resp, seed.german) as Seed['article']);
      } catch (err) {
        await sleep(500 * (attempt + 1));
      }
    }

    if (!mongolian) { failures.push(seed.german); console.warn(`  ✗ no gloss: ${seed.german}`); }
    else console.log(`  ✓ ${seed.german} → ${mongolian}`);

    out.push({
      german: seed.german,
      ...(article ? { article } : {}),
      mongolian,
      category: categoryFor(seed),
      exampleGerman: prior?.exampleGerman ?? '',
      exampleMongolian: prior?.exampleMongolian ?? '',
      wordClass: seed.wordClass,
      level: seed.level,
    });
    await sleep(250); // be gentle on the dictionary
  }

  // Only ship dictionary-backed words: an entry with no Mongolian gloss would
  // fall back to nothing in the trainer, so we drop it (and retry it next run).
  const shipped = out.filter((e) => e.mongolian);
  save(shipped);
  console.log(`\nWrote ${shipped.length} dictionary-backed entries (of ${out.length} candidates) → ${path.relative(process.cwd(), OUT_FILE)}`);
  if (failures.length) console.log(`Not in Bolor-toli (${failures.length}, skipped): ${failures.join(', ')}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
